### ISSUE TITLE
Update to use lycan 1.0.0

### ISSUE THREAD

**Issue by mstair** [newcontext-oss/openc2-aws-actuator#1]
Lycan has been updated based on CSD04, update usage

**Comment by mstair** [comment]
@jmgnc you can assign this to me

**Comment by mstair** [comment]
At this point it makes sense to defer until lycan updated for the OpenC2 1.0 spec. There are some significant structural changes from CSD04 (header is gone,etc).

**Comment by mstair** [comment]
Lycan 1.0.0 update (to utilize STIX2 python lib) will be merged soon.

**Comment by jmgnc** [comment]
This should be fixed in https://github.com/newcontext-oss/openc2-aws-actuator/commit/0b6ebeb0a182f1e28c34574ba5153d67ee34068c
